<?php

namespace App\Filament\Resources\ContactlistResource\Pages;

use App\Filament\Resources\ContactlistResource;
use App\Models\Contactlist;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateContactlist extends CreateRecord
{

    protected static string $resource = ContactlistResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Add new Contact";
    }



    protected function getCreateAnotherFormAction(): Action
    {
        return parent::getCreateAnotherFormAction()
            ->label('Add & add another'); // TODO: Change the autogenerated stub
    }

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()
            ->label('Add'); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();

        $existingContact = Contactlist::where('contact_id', $data['contact_id'])
            ->where('user_id', $data['user_id'])
            ->exists();
        if ($existingContact) {
            Notification::make()
                ->warning()
                ->title('Contact already exists!')
                ->persistent()
                ->send();
            $this->halt();
        }
        return $data;
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
